#!/usr/bin/python3
""" Script that reads stdin line by line and computes metrics """

import fileinput
import sys

total_size = 0  # total size of file
status_codes = {}  # status codes and its count
line_count = 0  # number of lines read

try:
    for line in fileinput.input():
        line_count += 1 # increment line count
        fields = line.split()  # split line into fields
        if len(fields) == 9:
            ip, _, _,date, _, request, status, _, size = fields  # unpack fields
            total_size += int(size)  # add size to total size
            status_codes[status] = status_codes.get(status, 0) + 1  # add status code to dict or increment count
        if line_count % 10 == 0:
            print(f"File size: {total_size}") # print total size
except KeyboardInterrupt:
    print(f"Total file size: File size: {total_size}")  # print total size
    for code in sorted(status_codes):
        print(f"{code}: {status_codes[code]}")
    sys.exit(0)



